events {}

http {
    server {
        listen 80;
        server_name booking-project.de www.booking-project.de;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name booking-project.de www.booking-project.de;

        location / {
            proxy_pass http://booking_back:8000/;
        }
        ssl_certificate /etc/letsencrypt/live/booking-project.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/booking-project.de/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    }
}